//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWeb5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Proyecto_2022Entities2 : DbContext
    {
        public Proyecto_2022Entities2()
            : base("name=Proyecto_2022Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C01_0_Personas> C01_0_Personas { get; set; }

        public System.Data.Entity.DbSet<AppWeb5.Models.ViewModels.PersonasViewModel> PersonasViewModels { get; set; }
    }
}
